In [2]:
import pandas as pd

df = pd.read_csv("../data/India_Flood_Inventory_v3.csv")

df.head()

,Unnamed: 0,UEI,Start Date,End Date,Duration(Days),Main Cause,Location,Districts,State,Latitude,...,Human fatality,Human injured,Human Displaced,Animal Fatality,Description of Casualties/injured,Extent of damage,Event Source,Event Souce ID,District_LGD_Codes,State_Codes
0,563,UEI-IMD-FL-1967-0001,02-07-1967 00:00,08-07-1967 00:00,7.0,flood,NaN,NaN,Assam,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,IMD,NaN,NaN,18
1,564,UEI-IMD-FL-1967-0002,22-07-1967 00:00,28-07-1967 00:00,7.0,flood,NaN,NaN,"Maharashtra, Gujarat",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,IMD,NaN,NaN,"27,24"
2,565,UEI-IMD-FL-1967-0003,01-08-1967 00:00,30-08-1967 00:00,30.0,flood,NaN,NaN,Uttar Pradesh,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,IMD,NaN,NaN,9
3,566,UEI-IMD-FL-1967-0004,08-09-1967 00:00,09-09-1967 00:00,2.0,flood,NaN,"Bhadrak, Dhenkanal, Jajapur, Subarnapur, Nuapa...","Odisha, Bihar, Uttar Pradesh, Madhya Pradesh, ...",NaN,...,NaN,NaN,NaN,NaN,NaN,Marooning of Barwer Express,IMD,NaN,"348, 352, 356, None, 368, 345, 349, 350, 359, ...","21,10,9,23,8,6"
4,567,UEI-IMD-FL-1968-0001,22-06-1968 00:00,28-06-1968 00:00,7.0,flood,NaN,NaN,Assam,NaN,...,NaN,NaN,NaN,NaN,NaN,"Affecting about one million people,an area of ...",IMD,NaN,NaN,18

In [ ]:
df.columns

Index(['Unnamed: 0', 'UEI', 'Start Date', 'End Date', 'Duration(Days)',
       'Main Cause', 'Location', 'Districts', 'State', 'Latitude', 'Longitude',
       'Severity', 'Area Affected', 'Human fatality', 'Human injured',
       'Human Displaced', 'Animal Fatality',
       'Description of Casualties/injured', 'Extent of damage ',
       'Event Source', 'Event Souce ID', 'District_LGD_Codes', 'State_Codes'],
      dtype='object')

In [6]:
columns_to_remove = [
"Unnamed: 0",
"UEI",
"End Date",
"Location",
"Animal Fatality",
"Description of Casualties/injured",
"Extent of damage",
"Event Source",
"Event Souce ID",
"District_LGD_Codes",
"State_Codes",
"Human injured"
]

df = df.drop(columns=columns_to_remove, errors="ignore")

In [7]:
df.head()

,Start Date,Duration(Days),Main Cause,Districts,State,Latitude,Longitude,Severity,Area Affected,Human fatality,Human Displaced,Extent of damage
0,02-07-1967 00:00,7.0,flood,NaN,Assam,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,22-07-1967 00:00,7.0,flood,NaN,"Maharashtra, Gujarat",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01-08-1967 00:00,30.0,flood,NaN,Uttar Pradesh,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,08-09-1967 00:00,2.0,flood,"Bhadrak, Dhenkanal, Jajapur, Subarnapur, Nuapa...","Odisha, Bihar, Uttar Pradesh, Madhya Pradesh, ...",NaN,NaN,NaN,NaN,NaN,NaN,Marooning of Barwer Express
4,22-06-1968 00:00,7.0,flood,NaN,Assam,NaN,NaN,NaN,NaN,NaN,NaN,"Affecting about one million people,an area of ..."

In [8]:
df = df.dropna(subset=["Latitude","Longitude"])

In [9]:
df.shape

(0, 12)

In [10]:
df["Latitude"] = pd.to_numeric(df["Latitude"], errors="coerce")
df["Longitude"] = pd.to_numeric(df["Longitude"], errors="coerce")

In [11]:
df["Start Date"] = pd.to_datetime(df["Start Date"], errors="coerce")

df["Year"] = df["Start Date"].dt.year

In [12]:
df = df.drop(columns=["Start Date"])

In [13]:
df = df.drop_duplicates()

In [14]:
df.to_csv("../data/clean_flood_dataset.csv", index=False)

In [ ]:
#second Datasets
import pandas as pd
rain = pd.read_csv("../data/Daily-rainfall-at-state-level.csv")
rain.head()

,id,date,state_code,state_name,actual,rfs,normal,deviation
0,0,2009-01-01,5,Uttarakhand,0.0,0.003906,2.19,-100.0
1,1,2009-01-01,18,Assam,0.0,0.000000,0.52,-100.0
2,2,2009-01-01,16,Tripura,0.0,0.000000,0.09,-100.0
3,3,2009-01-01,36,Telangana,0.0,0.000000,0.17,-100.0
4,4,2009-01-01,2,Himachal Pradesh,0.0,0.008566,3.31,-100.0

In [17]:
rain.shape

(204876, 8)

In [18]:
rain = pd.read_csv("../data/Daily-rainfall-at-state-level.csv")
print(rain.columns)

Index(['id', 'date', 'state_code', 'state_name', 'actual', 'rfs', 'normal',
       'deviation'],
      dtype='object')

In [19]:
rain.shape

(204876, 8)

In [20]:
rain["date"] = pd.to_datetime(rain["date"])
rain["year"] = rain["date"].dt.year
rain["month"] = rain["date"].dt.month

In [21]:
rain.head()

,id,date,state_code,state_name,actual,rfs,normal,deviation,year,month
0,0,2009-01-01,5,Uttarakhand,0.0,0.003906,2.19,-100.0,2009,1
1,1,2009-01-01,18,Assam,0.0,0.000000,0.52,-100.0,2009,1
2,2,2009-01-01,16,Tripura,0.0,0.000000,0.09,-100.0,2009,1
3,3,2009-01-01,36,Telangana,0.0,0.000000,0.17,-100.0,2009,1
4,4,2009-01-01,2,Himachal Pradesh,0.0,0.008566,3.31,-100.0,2009,1

In [22]:
rain = rain.drop(columns=["id","state_code","rfs","date"])

In [23]:
def rainfall_risk(dev):
    if dev > 60:
        return 3   # extreme rain
    elif dev > 20:
        return 2   # high rain
    elif dev > -20:
        return 1   # normal
    else:
        return 0   # low rain

rain["rain_risk"] = rain["deviation"].apply(rainfall_risk)

In [24]:
rain.head()

         state_name  actual  normal  deviation  year  month  rain_risk
0       Uttarakhand     0.0    2.19     -100.0  2009      1          0
1             Assam     0.0    0.52     -100.0  2009      1          0
2           Tripura     0.0    0.09     -100.0  2009      1          0
3         Telangana     0.0    0.17     -100.0  2009      1          0
4  Himachal Pradesh     0.0    3.31     -100.0  2009      1          0

In [25]:
rain_state = rain.groupby("state_name").agg({
    "actual":"mean",
    "normal":"mean",
    "deviation":"mean",
    "rain_risk":"mean"
}).reset_index()

In [26]:
rain_state.head()

                    state_name    actual    normal  deviation  rain_risk
0  Andaman And Nicobar Islands       NaN  7.913974        NaN   0.000000
1               Andhra Pradesh  2.567077  2.348395  33.046157   0.716921
2            Arunachal Pradesh  6.525427  8.262592 -18.568494   0.630118
3                        Assam  5.324927  6.255015 -15.577227   0.629239
4                        Bihar  3.021938  3.333360  18.814565   0.541205

In [29]:
rain_state.to_csv("../data/rainfall_processed.csv",index=False)

In [3]:
#3rd datasets
import pandas as pd
elev = pd.read_csv("../data/Districts_elevation.csv")
elev.head()

     District   Latitude  Longitude  elevation
0    Adilabad  19.663259  78.555315        256
1        Agra  27.175680  78.008109        170
2   Ahmadabad  23.026157  72.589687         51
3  Ahmadnagar  19.093412  74.746855        657
4      Aizawl  23.748659  92.728016        937

In [4]:
elev.shape

(626, 4)

In [5]:
elev.columns = elev.columns.str.lower()
elev.head()

     district   latitude  longitude  elevation
0    Adilabad  19.663259  78.555315        256
1        Agra  27.175680  78.008109        170
2   Ahmadabad  23.026157  72.589687         51
3  Ahmadnagar  19.093412  74.746855        657
4      Aizawl  23.748659  92.728016        937

In [6]:
elev = elev.dropna()

In [7]:
elev.shape

(626, 4)

In [8]:
def elevation_risk(e):
    if e < 100:
        return 2
    elif e < 300:
        return 1
    else:
        return 0

elev["terrain_risk"] = elev["elevation"].apply(elevation_risk)

In [9]:
elev.head()

     district   latitude  longitude  elevation  terrain_risk
0    Adilabad  19.663259  78.555315        256             1
1        Agra  27.175680  78.008109        170             1
2   Ahmadabad  23.026157  72.589687         51             2
3  Ahmadnagar  19.093412  74.746855        657             0
4      Aizawl  23.748659  92.728016        937             0

In [10]:
elev.to_csv("../data/elevation_processed.csv", index=False)

In [15]:
import pandas as pd
rain = pd.read_csv("../data/rainfall_processed.csv")
elev = pd.read_csv("../data/elevation_processed.csv")
rain.head()

                    state_name    actual    normal  deviation  rain_risk
0  Andaman And Nicobar Islands       NaN  7.913974        NaN   0.000000
1               Andhra Pradesh  2.567077  2.348395  33.046157   0.716921
2            Arunachal Pradesh  6.525427  8.262592 -18.568494   0.630118
3                        Assam  5.324927  6.255015 -15.577227   0.629239
4                        Bihar  3.021938  3.333360  18.814565   0.541205

In [16]:
elev.head()

     district   latitude  longitude  elevation  terrain_risk
0    Adilabad  19.663259  78.555315        256             1
1        Agra  27.175680  78.008109        170             1
2   Ahmadabad  23.026157  72.589687         51             2
3  Ahmadnagar  19.093412  74.746855        657             0
4      Aizawl  23.748659  92.728016        937             0

In [ ]:
elev["state_name"] = elev["district"]

In [17]:
flood_data = pd.merge(
    elev,
    rain,
    on="state_name",
    how="left"
)

flood_data.head()

KeyError: 'state_name'

In [20]:
elev["state_name"] = None

In [21]:
elev.loc[elev["district"]=="Agra","state_name"]="Uttar Pradesh"
elev.loc[elev["district"]=="Ahmadabad","state_name"]="Gujarat"
elev.loc[elev["district"]=="Ahmadnagar","state_name"]="Maharashtra"
elev.loc[elev["district"]=="Aizawl","state_name"]="Mizoram"
elev.loc[elev["district"]=="Adilabad","state_name"]="Telangana"

In [22]:
elev.head()

     district   latitude  longitude  elevation  terrain_risk     state_name
0    Adilabad  19.663259  78.555315        256             1      Telangana
1        Agra  27.175680  78.008109        170             1  Uttar Pradesh
2   Ahmadabad  23.026157  72.589687         51             2        Gujarat
3  Ahmadnagar  19.093412  74.746855        657             0    Maharashtra
4      Aizawl  23.748659  92.728016        937             0        Mizoram

In [23]:
flood_data = pd.merge(
    elev,
    rain,
    on="state_name",
    how="left"
)

In [24]:
flood_data.head()

,district,latitude,longitude,elevation,terrain_risk,state_name,actual,normal,deviation,rain_risk
0,Adilabad,19.663259,78.555315,256,1,Telangana,2.822724,2.563615,54.534313,0.622562
1,Agra,27.175680,78.008109,170,1,Uttar Pradesh,2.210868,2.666100,21.848970,0.503954
2,Ahmadabad,23.026157,72.589687,51,2,Gujarat,2.204378,1.939882,103.357637,0.418204
3,Ahmadnagar,19.093412,74.746855,657,0,Maharashtra,3.155383,3.118525,6.485008,0.651028
4,Aizawl,23.748659,92.728016,937,0,Mizoram,5.541335,5.974855,21.048367,0.588473

In [25]:
flood_data["flood_risk_score"] = flood_data["terrain_risk"] + flood_data["rain_risk"]

In [26]:
def flood_label(score):
    if score >= 4:
        return 3
    elif score >= 2:
        return 2
    elif score >= 1:
        return 1
    else:
        return 0

flood_data["flood_risk"] = flood_data["flood_risk_score"].apply(flood_label)

In [27]:
flood_data.shape

(626, 12)

In [30]:
import pandas as pd
rain = pd.read_csv("../data/rainfall_processed.csv")
elev = pd.read_csv("../data/elevation_processed.csv")
rain.head()

                    state_name    actual    normal  deviation  rain_risk
0  Andaman And Nicobar Islands       NaN  7.913974        NaN   0.000000
1               Andhra Pradesh  2.567077  2.348395  33.046157   0.716921
2            Arunachal Pradesh  6.525427  8.262592 -18.568494   0.630118
3                        Assam  5.324927  6.255015 -15.577227   0.629239
4                        Bihar  3.021938  3.333360  18.814565   0.541205

In [31]:
elev.head()

     district   latitude  longitude  elevation  terrain_risk
0    Adilabad  19.663259  78.555315        256             1
1        Agra  27.175680  78.008109        170             1
2   Ahmadabad  23.026157  72.589687         51             2
3  Ahmadnagar  19.093412  74.746855        657             0
4      Aizawl  23.748659  92.728016        937             0

In [32]:
rain = rain.rename(columns={"state_name":"state"})

In [33]:
flood_data = elev.copy()
# temporary rainfall mapping
flood_data["actual_rainfall"] = rain["actual"].mean()
flood_data["rain_deviation"] = rain["deviation"].mean()
flood_data["rain_risk"] = rain["rain_risk"].mean()

flood_data.head()

,district,latitude,longitude,elevation,terrain_risk,actual_rainfall,rain_deviation,rain_risk
0,Adilabad,19.663259,78.555315,256,1,3.990693,44.364785,0.539126
1,Agra,27.175680,78.008109,170,1,3.990693,44.364785,0.539126
2,Ahmadabad,23.026157,72.589687,51,2,3.990693,44.364785,0.539126
3,Ahmadnagar,19.093412,74.746855,657,0,3.990693,44.364785,0.539126
4,Aizawl,23.748659,92.728016,937,0,3.990693,44.364785,0.539126

In [34]:
flood_data["flood_risk_score"] = (
    flood_data["terrain_risk"] + flood_data["rain_risk"]
)

In [35]:
def flood_label(score):
    if score >= 3:
        return 3
    elif score >= 2:
        return 2
    elif score >= 1:
        return 1
    else:
        return 0

flood_data["flood_risk"] = flood_data["flood_risk_score"].apply(flood_label)

In [37]:
features = flood_data[[
    "latitude",
    "longitude",
    "elevation",
    "terrain_risk",
    "rain_risk"
]]

target = flood_data["flood_risk"]

In [38]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
X_train, X_test, y_train, y_test = train_test_split(
    features,
    target,
    test_size=0.2,
    random_state=42
)

model = RandomForestClassifier(n_estimators=200)

model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200)

In [39]:
from sklearn.metrics import accuracy_score
pred = model.predict(X_test)
accuracy_score(y_test, pred)

1.0

In [42]:
import joblib
joblib.dump(model,"../models/flood_ml_model.pkl")
joblib.dump(features.columns.tolist(),"../models/flood_model_features.pkl")

['../models/flood_model_features.pkl']

In [45]:
import pandas as pd
data = pd.read_csv("../data/elevation_processed.csv")
data.head()

     district   latitude  longitude  elevation  terrain_risk
0    Adilabad  19.663259  78.555315        256             1
1        Agra  27.175680  78.008109        170             1
2   Ahmadabad  23.026157  72.589687         51             2
3  Ahmadnagar  19.093412  74.746855        657             0
4      Aizawl  23.748659  92.728016        937             0

In [46]:
data.shape

(626, 5)

In [50]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=25, random_state=42)
data["cluster"] = kmeans.fit_predict(features)

In [51]:
hotspots = data.groupby("cluster").agg({
    "terrain_risk":"mean",
    "district":"count"
}).reset_index()

hotspots.rename(columns={"district":"district_count"}, inplace=True)

hotspots.head()

   cluster  terrain_risk  district_count
0        0      0.185185              27
1        1      0.000000               9
2        2      0.794118              34
3        3      1.533333              30
4        4      0.315789              19

In [ ]:
features = data[["latitude","longitude","terrain_risk"]]

In [52]:
data.to_csv("../data/flood_hotspots.csv", index=False)

In [53]:
data["readiness_score"] = 100 - (data["terrain_risk"] * 30)

In [54]:
import pandas as pd
data = pd.read_csv("../data/elevation_processed.csv")
data.head()

     district   latitude  longitude  elevation  terrain_risk
0    Adilabad  19.663259  78.555315        256             1
1        Agra  27.175680  78.008109        170             1
2   Ahmadabad  23.026157  72.589687         51             2
3  Ahmadnagar  19.093412  74.746855        657             0
4      Aizawl  23.748659  92.728016        937             0

In [55]:
import numpy as np

micro_points = []

for _, row in data.iterrows():
    for i in range(5):   # 5 micro hotspots per district
        lat = row["latitude"] + np.random.uniform(-0.05,0.05)
        lon = row["longitude"] + np.random.uniform(-0.05,0.05)

        micro_points.append({
            "district": row["district"],
            "latitude": lat,
            "longitude": lon,
            "terrain_risk": row["terrain_risk"]
        })

micro_hotspots = pd.DataFrame(micro_points)

micro_hotspots.head()

   district   latitude  longitude  terrain_risk
0  Adilabad  19.662930  78.521573             1
1  Adilabad  19.699517  78.598872             1
2  Adilabad  19.707106  78.547292             1
3  Adilabad  19.677515  78.573341             1
4  Adilabad  19.623061  78.546449             1

In [56]:
micro_hotspots.shape

(3130, 4)

In [57]:
from sklearn.cluster import KMeans
features = micro_hotspots[["latitude","longitude","terrain_risk"]]
kmeans = KMeans(n_clusters=60, random_state=42)
micro_hotspots["cluster"] = kmeans.fit_predict(features)
micro_hotspots.head()

   district   latitude  longitude  terrain_risk  cluster
0  Adilabad  19.662930  78.521573             1       18
1  Adilabad  19.699517  78.598872             1       18
2  Adilabad  19.707106  78.547292             1       18
3  Adilabad  19.677515  78.573341             1       18
4  Adilabad  19.623061  78.546449             1       18

In [58]:
zones = micro_hotspots.groupby("cluster").agg({
    "terrain_risk":"mean",
    "district":"count"
}).reset_index()
zones.rename(columns={"district":"hotspot_count"}, inplace=True)
zones.head()

   cluster  terrain_risk  hotspot_count
0        0      0.083333             60
1        1      0.000000             45
2        2      1.000000            125
3        3      1.000000             65
4        4      0.625000             40

In [59]:
zones["readiness_score"] = 100 - (zones["terrain_risk"] * 30)

In [60]:
micro_hotspots.to_csv("../data/india_flood_micro_hotspots.csv", index=False)
zones.to_csv("../data/flood_zone_summary.csv", index=False)